//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_thue_sach.Rela_tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSach()
        {
            this.tblCTHDThue = new HashSet<tblCTHDThue>();
            this.tblCTHDTra = new HashSet<tblCTHDTra>();
        }
    
        public string Masach { get; set; }
        public string Tensach { get; set; }
        public string Maloai { get; set; }
        public string Malinhvuc { get; set; }
        public string Matacgia { get; set; }
        public string MaNXB { get; set; }
        public string Mangonngu { get; set; }
        public double Sotrang { get; set; }
        public double Giasach { get; set; }
        public double Dongiathue { get; set; }
        public double Soluong { get; set; }
        public string Anh { get; set; }
        public string Ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCTHDThue> tblCTHDThue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCTHDTra> tblCTHDTra { get; set; }
        public virtual tblLinhvuc tblLinhvuc { get; set; }
        public virtual tblLoaisach tblLoaisach { get; set; }
        public virtual tblNXB tblNXB { get; set; }
        public virtual tblNgonngu tblNgonngu { get; set; }
        public virtual tblTacgia tblTacgia { get; set; }
    }
}
