//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_thue_sach.Rela_tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHDTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHDTra()
        {
            this.tblCTHDTra = new HashSet<tblCTHDTra>();
        }
    
        public string Matra { get; set; }
        public string Mathue { get; set; }
        public string MaNV { get; set; }
        public System.DateTime Ngaytra { get; set; }
        public double Tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCTHDTra> tblCTHDTra { get; set; }
        public virtual tblHDThue tblHDThue { get; set; }
        public virtual tblNV tblNV { get; set; }
    }
}
