//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_thue_sach.Rela_tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCTHDThue
    {
        public string Mathue { get; set; }
        public string Masach { get; set; }
        public string MaTT { get; set; }
        public string Datra { get; set; }
    
        public virtual tblSach tblSach { get; set; }
        public virtual tblHDThue tblHDThue { get; set; }
        public virtual tblTinhtrang tblTinhtrang { get; set; }
    }
}
